<div style="color:red">{{ errorMessage }}</div>
<div style="color:blue">{{ noticeMessage }}</div>
<Form action="/login" method="post">
    <label for="email">Email</label>
    <input type="email" name="email" value="{{ email }}" required/><br/>
    <label for="pass">Password</label>
    <input type="password" name="pass" required/><br/>

    <input type="submit" name="Login" value="Login"/>
</Form>