<div style="color:red">{{ errorMessage }}</div>
<div style="color:blue">{{ noticeMessage }}</div>
<Form method="post">
    <label for="email">Email</label>
    <input type="text" name="email" value="{{ email }}"/><br/>
    <label for="name">Name</label>
    <input type="text" name="name" value="{{ name }}"/><br/>
    <label for="pass">Password</label>
    <input type="text" name="pass"/><br/>
    <label for="passconfirm">Confirm Password</label>
    <input type="text" name="passconfirm"/><br/>

    <input type="submit" value="Register"/>
</Form>