<div style="color:red">{{ errorMessage }}</div>
<div style="color:blue">{{ noticeMessage }}</div>
<Form method="post">
    <label for="email">Email</label>
    <input type="email" name="email" value="{{ email }}" required/><br/>
    <label for="name">Name</label>
    <input type="text" name="name" value="{{ name }}" required/><br/>
    <label for="pass">Password</label>
    <input type="password" name="pass" required/><br/>
    <label for="passconfirm">Confirm Password</label>
    <input type="password" name="passconfirm" required/><br/>

    <input type="submit" value="Register"/>
</Form>